name: Attach Engine File Assets

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:    
  zip_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: git submodule update --init --recursive

      - uses: papeloto/action-zip@v1
        with:
          files: data/
          recursive: false
          dest: nlpengine.zip
          
      - uses: actions/upload-artifact@v4
        with:
          name: nlpengine.zip
          path: ${{ github.workspace }}/nlpengine.zip
