name: Attach Released Assets

on: [push]

jobs:    
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: analyzers/ data/ visualtext/
          recursive: true
          dest: visualtext.zip
          
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/visualtext.zip
